version: '3.8'

services:
  # --- SERVICIO FRONTEND (Angular) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whistle-front
    restart: always
    ports:
      - "8080:80"
    networks:
      - whistle-net
    depends_on:
      - backend

  # --- SERVICIO BACKEND (SAP CAP) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whistle-back
    restart: always
    ports:
      - "4004:4004"
    networks:
      - whistle-net
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  whistle-net:
    driver: bridge
